In [1]:
import tensorflow as tf
from tensorflow.keras.layers import Flatten,Dense
import cv2
import os
import numpy as np

In [2]:
images = []
number_of_images = []
#load images
def load_images_from_folder(folders):
    count = 0
    for folder in folders:
        for filename in os.listdir(folder):
            img = cv2.imread(os.path.join(folder,filename))
            if img is not None:
                img = cv2.resize(img,(299,299))
                images.append(img)
                count = count + 1
        number_of_images.append(count)
        count = 0

In [3]:
#change file path this.
foldersname = ['./images/Cobra_Crop/Head','./images/KingCobra_Crop/Head','./images/BandedKrait_Crop/Head']
load_images_from_folder(foldersname)

X = np.array(images)
X = tf.keras.applications.inception_v3.preprocess_input(X, data_format=None) 

In [4]:
X

array([[[[-0.5294118 , -0.6313726 , -0.4588235 ],
         [-0.52156866, -0.6       , -0.4352941 ],
         [-0.5764706 , -0.60784316, -0.4352941 ],
         ...,
         [-0.19215685, -0.15294117, -0.10588235],
         [-0.21568626, -0.18431371, -0.14509803],
         [-0.25490195, -0.2235294 , -0.18431371]],

        [[-0.5294118 , -0.6313726 , -0.45098037],
         [-0.5294118 , -0.6       , -0.41960782],
         [-0.56078434, -0.58431375, -0.41176468],
         ...,
         [-0.16862744, -0.12941176, -0.08235294],
         [-0.18431371, -0.15294117, -0.11372548],
         [-0.21568626, -0.18431371, -0.14509803]],

        [[-0.5529412 , -0.62352943, -0.42745095],
         [-0.5686275 , -0.60784316, -0.41960782],
         [-0.5921569 , -0.5921569 , -0.41176468],
         ...,
         [-0.15294117, -0.10588235, -0.06666666],
         [-0.1607843 , -0.1372549 , -0.09019607],
         [-0.18431371, -0.15294117, -0.11372548]],

        ...,

        [[ 0.19215691,  0.254902  ,  0

In [5]:
#เตรียม output
def defined_output(number_of_images):
    for count,num in enumerate(number_of_images):
        for i in range(num):
            classes = len(number_of_images)
            output = np.zeros((classes,), dtype=int)
            output[count] = 1
            y.append(output)

In [6]:
y = []
defined_output(number_of_images)
y = np.array(y)

In [7]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [8]:
from tensorflow.keras.models import Sequential , Model
from tensorflow.keras.layers import Dense , Activation
from tensorflow.keras.layers import Dropout , GlobalAveragePooling2D
from tensorflow.keras.layers import Flatten
from tensorflow.keras.optimizers import SGD , RMSprop , Adadelta , Adam
from tensorflow.keras.layers import Conv2D , BatchNormalization
from tensorflow.keras.layers import MaxPooling2D

In [9]:
base_model = tf.keras.applications.InceptionV3(include_top=False, weights='imagenet', input_shape=(299,299,3))

base_model.trainable = False #Freeze Parameters

inputs = tf.keras.Input(shape=(299, 299, 3))
x = base_model(inputs, training=False)
x = GlobalAveragePooling2D()(x)
x = Dense(256, activation='relu')(x)
x = Dropout(0.5)(x)
x = Dense(256, activation='relu')(x)
x = Dropout(0.5)(x)
predictions = Dense(3, activation='softmax')(x)

In [10]:
model = Model(inputs, predictions)

In [11]:
base_learning_rate = 0.0001
model.compile(optimizer=tf.keras.optimizers.Adam(lr=base_learning_rate),
              loss=tf.keras.losses.CategoricalCrossentropy(from_logits=False),
              metrics=['accuracy'])

In [12]:
model.summary()

Model: "functional_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_2 (InputLayer)         [(None, 299, 299, 3)]     0         
_________________________________________________________________
inception_v3 (Functional)    (None, 8, 8, 2048)        21802784  
_________________________________________________________________
global_average_pooling2d (Gl (None, 2048)              0         
_________________________________________________________________
dense (Dense)                (None, 256)               524544    
_________________________________________________________________
dropout (Dropout)            (None, 256)               0         
_________________________________________________________________
dense_1 (Dense)              (None, 256)               65792     
_________________________________________________________________
dropout_1 (Dropout)          (None, 256)              

In [13]:
y

array([[1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1,

In [14]:
model.fit(X_train,y_train,batch_size=32,epochs=10,validation_split=0.2)

Epoch 1/10
3/3 [==============================] - 4s 1s/step - loss: 1.1007 - accuracy: 0.4217 - val_loss: 1.0717 - val_accuracy: 0.2857
Epoch 2/10
3/3 [==============================] - 3s 1s/step - loss: 1.0199 - accuracy: 0.4940 - val_loss: 1.0302 - val_accuracy: 0.2857
Epoch 3/10
3/3 [==============================] - 4s 1s/step - loss: 0.9397 - accuracy: 0.5663 - val_loss: 0.9963 - val_accuracy: 0.4286
Epoch 4/10
3/3 [==============================] - 4s 1s/step - loss: 0.9062 - accuracy: 0.5663 - val_loss: 0.9736 - val_accuracy: 0.5238
Epoch 5/10
3/3 [==============================] - 4s 1s/step - loss: 0.8007 - accuracy: 0.5904 - val_loss: 0.9419 - val_accuracy: 0.5238
Epoch 6/10
3/3 [==============================] - 4s 1s/step - loss: 0.7559 - accuracy: 0.6506 - val_loss: 0.9088 - val_accuracy: 0.5238
Epoch 7/10
3/3 [==============================] - 4s 1s/step - loss: 0.8276 - accuracy: 0.6145 - val_loss: 0.8602 - val_accuracy: 0.5238
Epoch 8/10
3/3 [=========================

In [15]:
model.predict(X_test)

array([[0.667365  , 0.30030432, 0.03233068],
       [0.44197473, 0.3735014 , 0.18452387],
       [0.18341714, 0.30637115, 0.51021177],
       [0.45720178, 0.47237054, 0.07042777],
       [0.5949184 , 0.32707354, 0.07800811],
       [0.6703958 , 0.3041611 , 0.02544316],
       [0.6439991 , 0.31557333, 0.04042761],
       [0.13720132, 0.20439525, 0.65840346],
       [0.26057938, 0.364446  , 0.3749746 ],
       [0.10246526, 0.20577802, 0.69175667],
       [0.65381956, 0.27204654, 0.07413396],
       [0.5116371 , 0.3652227 , 0.12314025],
       [0.6329991 , 0.32429734, 0.04270355],
       [0.15344635, 0.23104577, 0.6155079 ],
       [0.44248828, 0.35113707, 0.20637454],
       [0.7542046 , 0.21877046, 0.02702493],
       [0.37402636, 0.36562422, 0.2603494 ],
       [0.6343532 , 0.31896377, 0.04668305],
       [0.09984487, 0.25667146, 0.6434836 ],
       [0.7224035 , 0.2506542 , 0.02694229],
       [0.5986371 , 0.32550332, 0.07585965],
       [0.7929034 , 0.17913784, 0.02795879],
       [0.

In [16]:
model.evaluate(X_test,y_test)

2/2 [==============================] - 1s 560ms/step - loss: 0.6669 - accuracy: 0.6923


[0.6669186949729919, 0.692307710647583]

In [20]:
y_pred = model.predict(X_test)

In [35]:
count = 0
for i in range(len(y_pred)):
    prob_max = np.argmax(y_pred[i])
    if(y_pred[i][prob_max] > 0.5 and np.argmax(y_pred[i]) == np.argmax(y_test[i])):
        count = count + 1
        print(y_pred[i],y_test[i])

[0.44197473 0.3735014  0.18452387] [1 0 0]
[0.45720178 0.47237054 0.07042777] [0 1 0]
[0.6703958  0.3041611  0.02544316] [1 0 0]
[0.13720132 0.20439525 0.65840346] [0 0 1]
[0.10246526 0.20577802 0.69175667] [0 0 1]
[0.65381956 0.27204654 0.07413396] [1 0 0]
[0.6329991  0.32429734 0.04270355] [1 0 0]
[0.15344635 0.23104577 0.6155079 ] [0 0 1]
[0.44248828 0.35113707 0.20637454] [1 0 0]
[0.7542046  0.21877046 0.02702493] [1 0 0]
[0.09984487 0.25667146 0.6434836 ] [0 0 1]
[0.7929034  0.17913784 0.02795879] [1 0 0]
[0.434868   0.3761553  0.18897673] [1 0 0]
[0.72802925 0.24243179 0.02953895] [1 0 0]
[0.6789697 0.2777587 0.0432716] [1 0 0]
[0.74057114 0.23561129 0.0238175 ] [1 0 0]
[0.7075957  0.25415468 0.03824953] [1 0 0]
[0.8027136  0.17838725 0.01889914] [1 0 0]
[0.6279741  0.3222311  0.04979475] [1 0 0]
[0.15886739 0.2629916  0.57814103] [0 0 1]
[0.3602012  0.32063782 0.319161  ] [1 0 0]
[0.06094081 0.14397407 0.79508513] [0 0 1]
[0.13900535 0.27578008 0.58521456] [0 0 1]
[0.12349819 0.

In [36]:
print(len(y_test),count)

52 36


In [44]:
from sklearn.metrics import f1_score

f1_y_pred = []
for i in y_pred:
    f1_y_pred.append(np.argmax(i))
    
f1_y_test = []
for i in y_test:
    f1_y_test.append(np.argmax(i))

f1_score(f1_y_test, f1_y_pred, average='micro')

0.6923076923076923

In [39]:
print(f1_y)

[]
